version: '3'
services:
  db:
    image: postgres:latest
    container_name: db_app
    restart: always
    command: -p 7777
    environment:
      - PGDATA=/postgresql/data
    expose:
      - 7777
    ports:
      - 5432:7777
    volumes:
      - postgres:/postgresql/data
    env_file:
      - .env

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_app
    ports:
      - 5050:80
    env_file:
      - .env
    depends_on:
      - db

  app:
    container_name: main_app
    restart: always
    build:
      context: .
    command:
#      - chmod a+x ./scripts/*.sh && ./scripts/start-dev.sh
      - ./start-dev.sh
    ports:
      - 8000:8000
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db

volumes:
  postgres: