"""update

Revision ID: 009c3bc74a4f
Revises: 8e414af20332
Create Date: 2023-04-24 17:09:03.416591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '009c3bc74a4f'
down_revision = '8e414af20332'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
