"""update

Revision ID: cc90d5904cd1
Revises: 419e802bfcba
Create Date: 2023-04-24 15:00:01.747777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc90d5904cd1'
down_revision = '419e802bfcba'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'application', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'application', type_='unique')
    # ### end Alembic commands ###
